### ISSUE TITLE
Support using `<` to set up colspan

### ISSUE THREAD

**Issue by kherock** [nice-move/rehype-extended-table#1]
Hi, thanks for the helpful library. I was wondering if you'd be open to supporting the `<` character to set up `colspan`. I find the examples with `>` hard to read since it doesn't really align with the use of `^` for rowspan as a left-to-right, top-to-bottom reader.

I think the main example in the README is a bit easier to read if the column contents are shown in the left-most cell:

```
| Head 1       | Head 2       | Head 3       | Head 4       |
| ------------ | ------------ | ------------ | ------------ |
| Merged (2x1) | <            | Cell         | Cell         |
| Merged (1x3) | Merged (2x2) | <            | Cell         |
| ^            | ^            | <            | Cell         |
| ^            | Merged (3x1) | <            | <            |
```

**Comment by Airkro** [comment]
Add [options.mergeTo](https://github.com/show-docs/rehype-extended-table#optionsmergeto) in v0.1.2, now `<` is available when `options.mergeTo` === `left`, please send me feedback.
